Enoch/new venting
StudentOrganisationForAerospaceResearch/VanderAvionics pull request #14
Opened 2018-05-19 08:19 UTC by enochtsang

2018-05-19 17:09 UTC, NataliaPavlovic requested changes
The code does not compile because "'OxidizerTankConditionsData' has no member named 'oxidizerTankConditionsData_'" and you did not format the files.

2018-05-21 01:07 UTC, NataliaPavlovic approved these changes

2018-05-21 18:04 UTC, enochtsang commented
Build is failing for some strange reason I don't know why. Please ignore it, it builds and formats fine.

2018-05-21 22:01 UTC, NataliaPavlovic requested changes
Maybe code should be added to ensure venting valve is closed for all phases after PRELANCH? To confirm, is the Injection valve supposed to be closed during COAST and DROGUE_DESCENT? That is what is currently happening. Everything else works as expected.

2018-05-22 05:02 UTC, NataliaPavlovic approved these changes

2018-05-22 05:25 UTC, merged