blink led2 based on what flight phase the code is in
StudentOrganisationForAerospaceResearch/VanderAvionics pull request #4
Opened 2018-04-03 17:42 UTC by enochtsang

2018-04-04 16:56 UTC, NataliaPavlovic requested changes
LED2 blinks correctly for all phases except for MAIN_DESCENT, where it just stays off the entire time. The only time the sd card is being written to is in PRELAUNCH phase (I'm not sure if this is correct behaviour or not).

2018-04-04 16:56 UTC, NataliaP721 commented on Src/main.c
> +            HAL_GPIO_WritePin(LED2_GPIO_Port, LED2_Pin, 0);
Need to add delay after LED2 is turned off because otherwise the LED just stays on.

2018-04-05 05:23 UTC, ExtraGravity commented on Src/main.c
> +            HAL_GPIO_WritePin(LED2_GPIO_Port, LED2_Pin, 0);
I'll use those values.

2018-04-05 05:25 UTC, enochtsang commented
It's very strange that MAIN_DESCENT stays off, that needs to be looked into. The SD card should also be written for other phases, those problems need to be looked into.

2018-04-07 20:56 UTC, NataliaPavlovic approved these changes

2018-04-07 22:08 UTC, merged